#Problem : registering Entity Service , instead of Booking Service through yml file

server:
  port: ${PORT:8080}

spring:
  application:
    name: UberBookingService


  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true


